# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1ba42ffc-9bed-4c2f-8df8-2a8adb261983";
      fsType = "btrfs";
      options = [ "subvol=@,compress-force=zstd:1" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1ba42ffc-9bed-4c2f-8df8-2a8adb261983";
      fsType = "btrfs";
      options = [ "subvol=@home,compress-force=zstd:1" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F152-EFF9";
      fsType = "vfat";
    };

  fileSystems."/media/files" =
    { device = "/dev/disk/by-uuid/20a2d6c5-f6e0-48a3-ad1f-ad6510da02a1";
      fsType = "btrfs";
      options = [ "subvol=@files,compress-force=zstd:1" ];
    };

  fileSystems."/media/games" =
    { device = "/dev/disk/by-uuid/20a2d6c5-f6e0-48a3-ad1f-ad6510da02a1";
      fsType = "btrfs";
      options = [ "subvol=@games,compress-force=zstd:1" ];
    };

  fileSystems."/media/data" =
    { device = "/dev/disk/by-uuid/1ba42ffc-9bed-4c2f-8df8-2a8adb261983";
      fsType = "btrfs";
      options = [ "subvol=@data,compress-force=zstd:1" ];
    };

  swapDevices = [ ];

}
